# Generated by Django 2.1 on 2019-11-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MHFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formID', models.BigIntegerField()),
                ('username', models.BigIntegerField()),
                ('depression', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('date', models.DateField()),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('q10', models.PositiveSmallIntegerField()),
                ('q11', models.PositiveSmallIntegerField()),
                ('q12', models.PositiveSmallIntegerField()),
                ('q13', models.PositiveSmallIntegerField()),
                ('q14', models.PositiveSmallIntegerField()),
                ('q15', models.PositiveSmallIntegerField()),
                ('q16', models.PositiveSmallIntegerField()),
                ('q17', models.PositiveSmallIntegerField()),
                ('q18', models.PositiveSmallIntegerField()),
                ('q19', models.PositiveSmallIntegerField()),
                ('q20', models.PositiveSmallIntegerField()),
                ('q21', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
