# Generated by Django 2.1 on 2019-11-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealthform', '0002_auto_20191102_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhformdata',
            name='formID',
            field=models.CharField(max_length=20),
        ),
    ]
